sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t mycroft-docker-armhf .
  - docker run -d -p 127.0.0.1:8181:8181 --name docker-mycroft docker-mycroft-armhf

script:
  - docker ps | grep -q "mycroft-docker"
